export const inputFormElements = [
  {
    name: "firstName",
    placeholder: "Enter first name",
    label: "First Name",
    variant: "outlined",
    fullwidth: true,
    required: true,
    xs: 12,
    sm: 6,
    validation: [
      {
        max: "25",
        message: "Should be less than 25",
      },
      {
        min: "3",
        message: "Should be greater than 3",
      },
    ],
  },
  {
    name: "lastName",
    placeholder: "Enter last name",
    label: "Last Name",
    variant: "outlined",
    fullwidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "phone",
    type: "number",
    placeholder: "Enter phone number",
    label: "Phone Number",
    variant: "outlined",
    fullwidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "email",
    type: "email",
    placeholder: "Enter email",
    label: "Email",
    variant: "outlined",
    fullwidth: true,
    required: true,
    xs: 12,
    sm: 6,
  },
  {
    name: "ashiwn",
    placeholder: "Enter aswin",
    label: "First Name",
    variant: "outlined",
    fullwidth: true,
    required: true,
    xs: 12,
    sm: 6,
    validation: [
      {
        max: "25",
        message: "Should be less than 25",
      },
      {
        min: "3",
        message: "Should be greater than 3",
      },
    ],
  },
];
